import ReactPlayer from "react-player";
import styles from "./FeatureSpotlight.module.scss";

const FeatureSpotlight = ({ project }) =>
  project.features.map((feature, index) => (
    <div className={styles.container} style={{ textAlign: "start" }}>
      <h3 className={styles.title}>{feature.title}</h3>
      <p
        className={styles.description}
        dangerouslySetInnerHTML={{ __html: feature.description }}
        /* In this situation, the above line of code is not dangerous.
         * All data in this application is generated by me and is stored in my own database.
         * Thus, I don't have to worry about malicious user data being interpreted as code.
         *
         * If you're adapting this code to situations in which user data is involved, don't use dangerouslySetInnerHTML.
         *
         * You can read more about React's dangerouslySetInnerHTML here:
         * https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml.
         * Stay safe!*/
      />
      {feature.demoLink && (
        <>
          <h3 style={{ fontSize: "1.2rem" }}>Demo:</h3>
          <div className={styles.playerContainer}>
            <ReactPlayer url={feature.demoLink} controls={true} />
          </div>
        </>
      )}

      {index !== project.features.length - 1 && <hr />}
    </div>
  ));
export default FeatureSpotlight;
